### index
GET http://localhost:9501/users

### find
GET http://localhost:9501/users/1

### create
POST http://localhost:9501/users
Content-Type: application/json

{
  "first_name": "ilyas",
  "last_name": "deckers",
  "email": "fdsfs@mail.com",
  "password": "fdskfjlkdsjflkaj"
}

### update
PUT http://localhost:9501/users/2
Content-Type: application/json

{
  "first_name": "ilyas",
  "last_name": "deckers",
  "email": "deckers@mail.com",
  "password": "fdskfjlkdsjflkaj"
}