#!/usr/bin/env php
<?php
declare(strict_types=1);
require __DIR__ . '/vendor/autoload.php';

try {
    Ody\Core\Console\Console::init();
} catch (Exception $e) {
    echo 'Error: ' . $e->getMessage() . "\n";
}