#!/usr/bin/env php
<?php
declare(strict_types=1);

use DI\Container;
use Ody\Core\Foundation\App;
use Ody\Core\Foundation\Bootstrap;

require __DIR__ . '/vendor/autoload.php';

/*
 * create const's and definitions
 */
define('PROJECT_PATH' , realpath('./'));
const ODY_VERSION = '0.0.1';
const ENABLE = true;
const DISABLE = false;

$app = App::create(new Container());
$app->bind('runningInConsole', true);

Ody\Core\Foundation\Console\Console::init(
    Bootstrap::init($app)
);